# Generated by Django 5.2.7 on 2026-08-29 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_proposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='duration_days',
            field=models.PositiveIntegerField(default=7),
            preserve_default=False,
        ),
    ]
